### ISSUE TITLE
Fix webpage timeout issue when waiting for 2FA code

### ISSUE THREAD

**Issue by hschickdevs** [hschickdevs/ibeam#6]
The webpage times out after a while of waiting for the 2FA code.

**Comment by hschickdevs** [comment]
Create /start and /code commands on the bot.

When the bot sees a /start command, it will start the 2FA process by refreshing the page and fetching the most recent 2FA challenge key.

It will then send this key to the bot, where the user can use the challenge key to get the 2FA code, and send the code with the /code CODE command.

**Comment by hschickdevs** [comment]
**Another Issue to Fix While Working with the Telegram Handler:**

Page up
2022-04-30 00:00:47,180|E| Error encountered while acquiring 2FA code.
Traceback (most recent call last):
  File "/srv/ibeam/src/authenticate.py", line 320, in handle_two_fa
    two_fa_code = two_fa_handler.get_two_fa_code(challenge_string=challenge_string)
  File "/srv/ibeam/src/two_fa_handlers/telegram_msg_handler.py", line 34, in get_two_fa_code
    return self.await_2fa_code()
  File "/srv/ibeam/src/two_fa_handlers/telegram_msg_handler.py", line 82, in await_2fa_code
    timestamp = update['message']['date']
KeyError: 'message'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/srv/ibeam/src/authenticate.py", line 325, in handle_two_fa
    raise RuntimeError('Error encountered while acquiring 2FA code.') from two_fa_exception
RuntimeError: Error encountered while acquiring 2FA code.
2022-04-30 00:00:47,187|W| No 2FA code returned. Aborting authentication.
2022-04-30 00:01:00,209|E| Error displayed by the login webpage: failed
2022-04-30 00:01:00,226|C| ######## ATTENTION! ######## Maximum number of failed authentication attempts (IBEAM_MAX
_FAILED_AUTH=5) reached. IBeam will shut down to prevent an account lock-out. It is recommended you attempt to auth
enticate manually in order to reset the counter. Read the execution logs and report issues at https://github.com/Vo
yz/ibeam/issues
2022-04-30 00:01:01,323|I| Authentication process failed
2022-04-30 00:01:01,328|W| Shutting IBeam maintenance down due to exceeded number of failed attempts.
